#!/usr/bin/env python3
"""
Build SeACDroid context-subgraph features from static-analysis text files.

Input: static-analysis text files generated by extract_static_ir.py
Output: pkl files with API context subgraphs and node embeddings
"""

import os
import re
import pickle
import argparse
import logging
from pathlib import Path
from typing import Dict, Set, List, Tuple
from collections import defaultdict
from multiprocessing import Pool
from tqdm import tqdm
import numpy as np
import torch

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)


# ============================================================================
# Constants
# ============================================================================

ENTRY_TYPE_TO_IDX = {
    'Lifecycle': 0,
    'Callback': 1,
    'Runnable': 2,
    'Callable': 3,
    'StaticInit': 4,
    'Unknown': 5
}

# Meaningless APIs to filter
MEANINGLESS_APIS = {
    'Ljava/lang/Object;-><init>()V',
    'Ljava/lang/Object;->toString()Ljava/lang/String;',
    'Ljava/lang/Object;->equals(Ljava/lang/Object;)Z',
    'Ljava/lang/Object;->hashCode()I',
    'Ljava/lang/Object;->getClass()Ljava/lang/Class;',
}

# Global variables for multiprocessing
_security_relevant_apis = None
_official_packages = None


# ============================================================================
# Utility Functions
# ============================================================================

def smali_to_java(smali_sig: str) -> str:
    """Convert Smali signature to Java format."""
    if not smali_sig:
        return ''
    sig = smali_sig
    if sig.startswith('L'):
        sig = sig[1:]
    if '(' in sig:
        sig = sig.split('(')[0]
    sig = sig.replace('/', '.')
    sig = sig.replace(';', '.')
    sig = sig.replace('->', '.')
    sig = sig.replace('<', '.')
    sig = sig.replace('>', '.')
    while '..' in sig:
        sig = sig.replace('..', '.')
    if sig.endswith('.'):
        sig = sig[:-1]
    return sig


def split_camel_case(text: str) -> str:
    """Split camelCase into words."""
    if not text:
        return text
    text = re.sub(r'([a-z])([A-Z])', r'\1 \2', text)
    text = re.sub(r'([A-Z]+)([A-Z][a-z])', r'\1 \2', text)
    return text.lower()


def parse_signature(java_sig: str) -> dict:
    """Parse Java signature into components."""
    parts = java_sig.split('.')
    if len(parts) < 2:
        return {'package': '', 'class': '', 'method': java_sig}
    method_name = parts[-1].split('(')[0] if '(' in parts[-1] else parts[-1]
    class_idx = len(parts) - 2
    class_name = parts[class_idx] if class_idx >= 0 else ''
    return {'class': class_name, 'method': method_name}


def create_semantic_text(java_sig: str) -> str:
    """Generate semantic text for SBERT embedding."""
    parsed = parse_signature(java_sig)
    class_words = split_camel_case(parsed['class']) if parsed['class'] else ''
    method_words = split_camel_case(parsed['method'])
    if class_words:
        return f"{class_words} {method_words}"
    return method_words


def load_security_relevant_apis(api_path: str) -> Set[Tuple[str, str]]:
    """Load the security-relevant API set."""
    apis = set()
    with open(api_path, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            parts = line.rsplit('.', 1)
            if len(parts) == 2:
                class_full, method_name = parts
                dalvik_class = 'L' + class_full.replace('.', '/') + ';'
                apis.add((dalvik_class, method_name))
    return apis


def load_official_packages(pkg_file: str) -> Dict[str, List[str]]:
    """Load official package list."""
    packages = {}
    with open(pkg_file, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith('#'):
                dalvik_pkg = 'L' + line.replace('.', '/') + '/'
                top_level = dalvik_pkg.split('/')[0] + '/'
                if top_level not in packages:
                    packages[top_level] = []
                packages[top_level].append(dalvik_pkg)
    return packages


def is_official_api(sig: str) -> bool:
    """Check if signature is an official API."""
    if not sig:
        return False
    class_part = sig.split('->')[0] if '->' in sig else sig
    if '/' in class_part:
        top_level = class_part.split('/')[0] + '/'
    else:
        return False
    if top_level not in _official_packages:
        return False
    for pkg in _official_packages[top_level]:
        if class_part.startswith(pkg):
            return True
    return False


def is_security_relevant_api(sig: str) -> bool:
    """Check if a signature belongs to the security-relevant API set."""
    if '->' not in sig:
        return False
    class_part = sig.split('->')[0]
    method_part = sig.split('->')[1]
    method_name = method_part.split('(')[0]
    return (class_part, method_name) in _security_relevant_apis


def is_meaningless_api(sig: str) -> bool:
    """Check if API is meaningless."""
    return sig in MEANINGLESS_APIS



# ============================================================================
# Static-Analysis Text Parsing
# ============================================================================

def parse_static_ir_file(txt_path: str):
    """Parse one static-analysis text file."""
    entries = []
    entry_map = {}
    method_bodies = {}
    current_method = None
    current_apis = []
    
    with open(txt_path, 'r', encoding='utf-8', errors='ignore') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            parts = line.split('\t')
            if parts[0] == 'ENTRY' and len(parts) >= 3:
                sig, entry_type = parts[1], parts[2]
                entries.append((sig, entry_type))
                entry_map[sig] = entry_type
            elif parts[0] == 'METHOD_START' and len(parts) >= 2:
                current_method = parts[1]
                current_apis = []
            elif parts[0] == 'API' and len(parts) >= 2:
                current_apis.append(parts[1])
            elif parts[0] == 'METHOD_END':
                if current_method:
                    method_bodies[current_method] = current_apis
                current_method = None
                current_apis = []
    
    return entries, method_bodies, entry_map


def build_reverse_cg(method_bodies: Dict) -> Dict:
    """Build reverse call graph: callee -> [callers]."""
    method_set = set(method_bodies.keys())
    reverse_cg = defaultdict(list)
    for method, apis in method_bodies.items():
        for api in apis:
            if api in method_set:
                reverse_cg[api].append(method)
    return reverse_cg


# ============================================================================
# Subgraph Extraction
# ============================================================================

def flatten_with_topology(
    method_sig: str,
    method_bodies: Dict,
    visited: Set = None,
    max_depth: int = 5,
    current_penetration: int = 0
) -> Tuple[List[str], List[Tuple], Dict[str, int]]:
    """
    Recursively flatten method calls, returning official API sequence.
    
    Returns:
        (api_sequence, edges, node_depths)
    """
    if visited is None:
        visited = set()
    
    if method_sig in visited or max_depth <= 0:
        return [], [], {}
    
    visited.add(method_sig)
    
    if method_sig not in method_bodies:
        if is_official_api(method_sig):
            return [method_sig], [], {method_sig: current_penetration}
        return [], [], {}
    
    apis = method_bodies[method_sig]
    result_seq = []
    result_edges = []
    result_depths = {}
    last_official = None
    
    has_direct_official = any(
        is_official_api(api) and not is_meaningless_api(api) 
        for api in apis
    )
    
    for api in apis:
        if is_official_api(api):
            if is_meaningless_api(api):
                continue
            
            result_seq.append(api)
            if api not in result_depths or current_penetration < result_depths[api]:
                result_depths[api] = current_penetration
            
            if last_official:
                result_edges.append((last_official, api))
            last_official = api
            
        elif api in method_bodies:
            if not has_direct_official:
                continue
            
            sub_seq, sub_edges, sub_depths = flatten_with_topology(
                api, method_bodies, visited.copy(),
                max_depth - 1, current_penetration + 1
            )
            
            if sub_seq:
                if last_official:
                    result_edges.append((last_official, sub_seq[0]))
                result_seq.extend(sub_seq)
                result_edges.extend(sub_edges)
                for node, d in sub_depths.items():
                    if node not in result_depths or d < result_depths[node]:
                        result_depths[node] = d
                last_official = sub_seq[-1]
    
    return result_seq, result_edges, result_depths


def extract_single_subgraph(
    sink_api: str,
    direct_caller: str,
    upstream_caller: str,
    method_bodies: Dict,
    entry_map: Dict
) -> Dict:
    """Extract a single execution path subgraph."""
    nodes_ordered = []
    nodes_set = set()
    edges = []
    node_depths = {}
    
    def add_node(n, depth=0):
        if n not in nodes_set:
            nodes_set.add(n)
            nodes_ordered.append(n)
            node_depths[n] = depth
        elif depth < node_depths.get(n, 999):
            node_depths[n] = depth
    
    # Expand upstream caller (shallow)
    upstream_seq = []
    if upstream_caller:
        upstream_seq, upstream_edges, upstream_depths = flatten_with_topology(
            upstream_caller, method_bodies, max_depth=2, current_penetration=0
        )
        for n in upstream_seq:
            add_node(n, upstream_depths.get(n, 0))
        edges.extend(upstream_edges)
    
    # Expand direct caller (deep)
    direct_seq, direct_edges, direct_depths = flatten_with_topology(
        direct_caller, method_bodies, max_depth=999, current_penetration=0
    )
    for n in direct_seq:
        add_node(n, direct_depths.get(n, 0))
    edges.extend(direct_edges)
    
    # Ensure sink is in nodes
    add_node(sink_api, 0)
    
    # Connect upstream caller to direct caller
    if upstream_seq and direct_seq:
        edges.append((upstream_seq[-1], direct_seq[0]))
    
    # Deduplicate edges
    edges = list(set(edges))
    edges = [(s, d) for s, d in edges if s in nodes_set and d in nodes_set]
    
    if len(nodes_ordered) < 1:
        return None
    
    # Get entry type
    entry_types = set()
    if upstream_caller and upstream_caller in entry_map:
        entry_types.add(entry_map[upstream_caller])
    if direct_caller in entry_map:
        entry_types.add(entry_map[direct_caller])
    if not entry_types:
        entry_types = {'Unknown'}
    
    priority = {'Lifecycle': 0, 'Callback': 1, 'Runnable': 2, 'Callable': 3, 'StaticInit': 4, 'Unknown': 5}
    primary_entry_type = min(entry_types, key=lambda x: priority.get(x, 5))
    
    return {
        "anchor": sink_api,
        "entry_type": primary_entry_type,
        "nodes": nodes_ordered,
        "edges": edges,
        "penetration_depths": [node_depths.get(n, 0) for n in nodes_ordered]
    }



def dedup_subgraphs(subgraphs: List[Dict]) -> List[Dict]:
    """Deduplicate subgraphs by (nodes, edges)."""
    seen = set()
    unique = []
    
    for sg in subgraphs:
        nodes_key = tuple(sorted(sg['nodes']))
        edges_key = tuple(sorted(tuple(e) for e in sg['edges']))
        key = (nodes_key, edges_key)
        
        if key not in seen:
            seen.add(key)
            unique.append(sg)
    
    return unique


def extract_subgraphs_from_ir(txt_path: str) -> List[Dict]:
    """Extract all API context subgraphs from one static-analysis text file."""
    entries, method_bodies, entry_map = parse_static_ir_file(txt_path)
    
    if not method_bodies:
        return []
    
    reverse_cg = build_reverse_cg(method_bodies)
    
    # Find all paths to security-relevant APIs
    paths_by_anchor_direct = defaultdict(list)
    
    for method, apis in method_bodies.items():
        if 'support/' in method or 'androidx/' in method:
            continue
        
        for api in apis:
            if is_security_relevant_api(api) and is_official_api(api):
                callers = reverse_cg.get(method, [])
                callers = [c for c in callers if 'support/' not in c and 'androidx/' not in c]
                
                if callers:
                    paths_by_anchor_direct[(api, method)].extend(callers)
                else:
                    paths_by_anchor_direct[(api, method)].append(None)
    
    if not paths_by_anchor_direct:
        return []
    
    # Extract subgraphs
    subgraphs = []
    for (sink, direct_caller), upstream_callers in paths_by_anchor_direct.items():
        for upstream_caller in set(upstream_callers):
            sg = extract_single_subgraph(sink, direct_caller, upstream_caller, method_bodies, entry_map)
            if sg:
                subgraphs.append(sg)
    
    return dedup_subgraphs(subgraphs)


# ============================================================================
# Multiprocessing Worker
# ============================================================================

def init_worker(apis, official_pkgs):
    """Initialize worker process globals."""
    global _security_relevant_apis, _official_packages
    _security_relevant_apis = apis
    _official_packages = official_pkgs


def extract_worker(args):
    """Worker function for multiprocessing."""
    txt_path, label = args
    try:
        subgraphs = extract_subgraphs_from_ir(txt_path)
        if not subgraphs:
            return {
                'status': 'empty',
                'apk_hash': Path(txt_path).stem,
                'label': label,
                'subgraphs': [],
                'signatures': set()
            }
        
        all_sigs = set()
        for sg in subgraphs:
            all_sigs.update(sg['nodes'])
        
        return {
            'status': 'success',
            'apk_hash': Path(txt_path).stem,
            'label': label,
            'subgraphs': subgraphs,
            'signatures': all_sigs
        }
    except Exception as e:
        return {'status': 'failed', 'apk_hash': Path(txt_path).stem, 'error': str(e)}


# ============================================================================
# Stage 1: Extract Subgraphs
# ============================================================================

def stage1_extract(txt_dir: str, label: int, security_relevant_apis: Set, workers: int):
    """Stage 1: Extract context-subgraph structures from static-analysis text files."""
    txt_files = list(Path(txt_dir).glob('*.txt'))
    logger.info(f"Found {len(txt_files)} static-analysis text files")
    
    tasks = [(str(f), label) for f in txt_files]
    
    apk_data = {}
    all_signatures = set()
    stats = {'success': 0, 'empty': 0, 'failed': 0}
    
    with Pool(workers, initializer=init_worker, 
              initargs=(security_relevant_apis, _official_packages)) as pool:
        for result in tqdm(pool.imap_unordered(extract_worker, tasks),
                          total=len(tasks), desc="Extracting subgraphs"):
            status = result.get('status', 'failed')
            stats[status] = stats.get(status, 0) + 1
            
            if status == 'success':
                apk_data[result['apk_hash']] = {
                    'label': result['label'],
                    'subgraphs': result['subgraphs']
                }
                all_signatures.update(result['signatures'])
            elif status == 'empty':
                apk_data[result['apk_hash']] = {
                    'label': result['label'],
                    'subgraphs': []
                }
    
    logger.info(f"Stage 1 done: success={stats['success']}, empty={stats['empty']}, failed={stats['failed']}")
    logger.info(f"Total signatures: {len(all_signatures)}")
    
    return apk_data, all_signatures


# ============================================================================
# Stage 2: Generate Embeddings
# ============================================================================

def stage2_embed(all_signatures: Set[str], model_path: str) -> Dict[str, np.ndarray]:
    """Stage 2: Generate SBERT embeddings for all signatures."""
    from sentence_transformers import SentenceTransformer
    
    sig_list = sorted(all_signatures)
    logger.info(f"Generating embeddings for {len(sig_list)} signatures...")
    
    # Convert to semantic text
    texts = [create_semantic_text(smali_to_java(sig)) for sig in sig_list]
    
    # Load model and encode
    logger.info(f"Loading model: {model_path}")
    model = SentenceTransformer(model_path)
    
    embeddings = model.encode(
        texts,
        batch_size=256,
        normalize_embeddings=True,
        show_progress_bar=True
    )
    
    sig_to_emb = {sig: emb for sig, emb in zip(sig_list, embeddings)}
    logger.info(f"Stage 2 done: embedding shape {embeddings.shape}")
    
    return sig_to_emb



# ============================================================================
# Stage 3: Assemble and Save
# ============================================================================

def stage3_save(apk_data: Dict, sig_to_emb: Dict, output_dir: str, year: str, label_name: str):
    """Stage 3: Assemble subgraphs with embeddings and save."""
    out_path = Path(output_dir) / year / label_name
    out_path.mkdir(parents=True, exist_ok=True)
    
    emb_dim = len(next(iter(sig_to_emb.values())))
    saved = 0
    empty = 0
    
    for apk_hash, data in tqdm(apk_data.items(), desc=f"Saving {year}/{label_name}"):
        subgraphs = data['subgraphs']
        label = data['label']
        
        if not subgraphs:
            empty += 1
            continue
        
        processed_subgraphs = []
        for sg in subgraphs:
            nodes = sg['nodes']
            edges = sg['edges']
            
            # Build node features
            node_features = []
            valid_nodes = []
            for node in nodes:
                if node in sig_to_emb:
                    node_features.append(sig_to_emb[node])
                    valid_nodes.append(node)
            
            if not node_features:
                continue
            
            node_features = np.array(node_features, dtype=np.float32)
            
            # Remap edges
            node_to_idx = {n: i for i, n in enumerate(valid_nodes)}
            valid_edges = []
            for src, dst in edges:
                if src in node_to_idx and dst in node_to_idx:
                    valid_edges.append([node_to_idx[src], node_to_idx[dst]])
            
            if valid_edges:
                edge_index = torch.tensor(valid_edges, dtype=torch.long).t().contiguous()
            else:
                # Self-loops if no edges
                n = len(valid_nodes)
                edge_index = torch.stack([torch.arange(n), torch.arange(n)], dim=0)
            
            processed_subgraphs.append({
                'node_features': torch.tensor(node_features),
                'edge_index': edge_index,
                'num_nodes': len(valid_nodes),
                'num_edges': edge_index.shape[1],
                'anchor': sg['anchor'],
                'entry_type': sg['entry_type'],
                'signatures': valid_nodes
            })
        
        if processed_subgraphs:
            output_file = out_path / f"{apk_hash}.pkl"
            with open(output_file, 'wb') as f:
                pickle.dump({
                    'label': label,
                    'subgraphs': processed_subgraphs
                }, f)
            saved += 1
    
    logger.info(f"Saved {saved} APKs, {empty} empty")
    return saved, empty


# ============================================================================
# Main
# ============================================================================

def main():
    parser = argparse.ArgumentParser(description='Build context-subgraph features from static-analysis text files')
    parser.add_argument('--input_root', required=True, help='Input root directory for static-analysis text files')
    parser.add_argument('--output_root', required=True, help='Output root directory (pkl files)')
    parser.add_argument(
        '--datasets',
        '--years',
        nargs='+',
        default=[str(year) for year in range(2011, 2022)],
        help='Dataset directories under input_root, e.g., 2021, 1112, or 11121314',
    )
    package_root = Path(__file__).resolve().parents[2]
    parser.add_argument('--security_relevant_api_list', default=str(package_root / 'data' / 'security_relevant_apis.txt'))
    parser.add_argument('--pkg_list', default=str(package_root / 'data' / 'official_packages.txt'))
    parser.add_argument('--model_path', default='all-MiniLM-L6-v2',
                        help='SBERT model path or name')
    parser.add_argument('--workers', type=int, default=8)
    args = parser.parse_args()
    
    global _official_packages
    
    # Load official packages
    _official_packages = load_official_packages(args.pkg_list)
    logger.info(f"Loaded {sum(len(v) for v in _official_packages.values())} official packages")
    
    # Load security-relevant APIs
    security_relevant_apis = load_security_relevant_apis(args.security_relevant_api_list)
    logger.info(f"Loaded {len(security_relevant_apis)} security-relevant APIs")
    
    # Stage 1: Extract all subgraphs
    logger.info("=" * 60)
    logger.info("Stage 1: Extracting subgraphs")
    logger.info("=" * 60)
    
    all_apk_data = {}
    global_signatures = set()
    
    for dataset_name in args.datasets:
        for label_name, label_val in [('benign', 0), ('malware', 1)]:
            input_dir = os.path.join(args.input_root, str(dataset_name), label_name)
            
            if not os.path.exists(input_dir):
                logger.warning(f"Skipping non-existent: {input_dir}")
                continue
            
            logger.info(f"\nProcessing {dataset_name}/{label_name}...")
            apk_data, sigs = stage1_extract(input_dir, label_val, security_relevant_apis, args.workers)
            
            for apk_hash, data in apk_data.items():
                all_apk_data[(dataset_name, label_name, apk_hash)] = data
            global_signatures.update(sigs)
    
    logger.info(f"\nStage 1 summary: {len(all_apk_data)} APKs, {len(global_signatures)} unique signatures")
    
    if not global_signatures:
        logger.error("No signatures found, exiting")
        return
    
    # Stage 2: Generate embeddings
    logger.info("=" * 60)
    logger.info("Stage 2: Generating embeddings")
    logger.info("=" * 60)
    
    sig_to_emb = stage2_embed(global_signatures, args.model_path)
    
    # Stage 3: Save
    logger.info("=" * 60)
    logger.info("Stage 3: Saving pkl files")
    logger.info("=" * 60)
    
    # Group by dataset directory and label.
    by_dataset_label = defaultdict(dict)
    for (dataset_name, label_name, apk_hash), data in all_apk_data.items():
        by_dataset_label[(dataset_name, label_name)][apk_hash] = data
    
    total_saved = 0
    total_empty = 0
    
    for (dataset_name, label_name), apk_data in by_dataset_label.items():
        saved, empty = stage3_save(apk_data, sig_to_emb, args.output_root, str(dataset_name), label_name)
        total_saved += saved
        total_empty += empty
    
    logger.info(f"\nDone! Total saved: {total_saved}, empty: {total_empty}")


if __name__ == '__main__':
    main()
